### ISSUE TITLE
Logfile/tracking Wikipedia usage

### ISSUE THREAD

**Issue by atharijeff** [offspot/kiwix-hotspot#612] opened 2021-06-21 15:12 UTC
The Literate Earth Project operates a network of 16 primary school based libraries in Uganda. We have been rolling out Raspberry Pi with Kiwix in those libraries, mainly to give students access to an offline version of Wikipedia.

We have major corporate of funders who want us to expand our work at other schools but we have no metrics, other than sign-up sheets for using the Raspberry Pi units, that students are utilizing it. We need some way to track searches and when a student clicks a hyperlink. Perhaps this could just be something that tracks each time the URL changes.

We have spoken with more seven organizations that also use this model in Uganda. They have said they would benefit from tracking. I have spoken with the Raspberry Pi's International Programme Manager, James Aslett. He also is not aware of a way to track this and notes the value for funders for organizations using Kiwix all over the world.

**Comment by rgaudin** [comment] 2021-06-21 15:54
That's something we want to do through #429. cc @Popolechien

**Comment by atharijeff** [comment] 2021-06-21 16:09
Fantastic. Glad there is other movement for this @rgaudin. Please let me know if you need me to delete this.

**Comment by Popolechien** [comment] 2021-06-29 12:38
See #510 as well.

**Comment by atharijeff** [comment] 2021-07-09 15:59
Per Stephane's guidance, elaborating here:

We ultimately need to track URL changes. That will allow us to understand how many searches or hyperlink clicks (which is basically a search/pulling up new info). It needs to be stored on a file that our staff can extract every three months when they visit the sites.

**Comment by kelson42** [comment] 2021-08-03 14:21
Seems a duplicate of #510

**Closed by kelson42** 2021-08-03 14:21 UTC
Labels: question
