### ISSUE TITLE
Error when trying to generate image using Windows desktop installer

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#633] opened 2022-02-01 11:11 UTC
From a user:
"unfortunatelly I am getting an error by trying to install kiwix by the
online installer: kiwix-hotspot-win64 

Machine: Win10 i3 and the other i5 Intel. Does not matter if I install
directly to SD or to a path. Sames error occurs.
![image003](https://user-images.githubusercontent.com/21675885/151956641-03479317-452a-4821-b653-f2335e7b0833.jpg)
```
[11:58:04] Getting output of ['wmic', 'partition']

[11:58:04] [STAGE 1/6: Retrieve Master Image - 0%]

[11:58:04] [STAGE 1/6: Retrieve Master Image - 0%]

[11:58:04] Preventing system from sleeping

[11:58:04] Setting ES_SYSTEM_REQUIRED mode to current thread

[11:58:04] --> Check System Requirements

[11:58:04] Please read
https://github.com/kiwix/kiwix-hotspot/wiki/System-Requirements for details

[11:58:04] --> Ensure user files are present

[11:58:04] --> Prepare Image file

[11:58:04] --> Dumping Hotspot Configuration

[11:58:04] {

"installer_version": "2.4.9",

"mirror": "http://download.kiwix.org",

"catalogs": [

{

"name": "Kiwix",

"description": "Kiwix ZIM Content",

"url": "http://mirror.download.kiwix.org/library/ideascube.yml",

"local_url": "file:///home/pi/catalog_Kiwix.yml"

}

],

"kernel_version": "5.10.17",

"root_partition_size": 7000000000,

"disk_size": 34359738368,

"project_name": "Free",

"timezone": "Europe/Berlin",

"language": "en",

"language_name": "English",

"kalite_languages": [],

"wikifundi_languages": [],

"aflatoun_languages": [],

"edupi": false,

"edupi_has_resources": false,

"nomad": false,

"mathews": false,

"africatik": false,

"packages": [

"wikipedia_de_basketball_maxi.de",

"wikipedia_de_basketball_nopic.de",

"wikipedia_de_football_maxi.de",

"wikipedia_de_football_nopic.de",

"wiktionary_de_all_maxi.de",

"wiktionary_de_all_nopic.de"

],

"custom_branding_path": "/tmp",

"admin_account": "admin",

"admin_password": "****"

}

[11:58:04] homepage saved to: C:\Users\koble\AppData\Local\Temp\tmpsjlpw13j.
html

[11:58:04] [STAGE 1/6: Retrieve Master Image - 0%]

[11:58:04] --> Retrieving base image file

[11:58:04] calculating sum for
D:\kiwix-hotspot.cache\kiwix-hotspot_master_2021-11-24.img.zip...[11:58:15]
MISMATCH.

[11:58:15] C:\Users\koble\AppData\Local\Temp\7zS2AC7.tmp\aria2c.exe --dir=D:
\kiwix-hotspot.cache --out=kiwix-hotspot_master_2021-11-24.img.zip
--connect-timeout=60 --max-file-not-found=5 --max-tries=5 --retry-wait=60
--timeout=60 --follow-metalink=mem --allow-overwrite=true
--always-resume=false --max-resume-failure-tries=1
--auto-file-renaming=false --download-result=full --log-level=error
--console-log-level=error --summary-interval=1 --human-readable=false
--ca-certificate=C:\Users\koble\AppData\Local\Temp\7zS2AC7.tmp\ca-certificat
es.crt
http://download.kiwix.org/release/kiwix-hotspot/master/kiwix-hotspot_master_
2021-11-24.img.zip

[11:58:15] [ ] 0%

```
**Note: Log was too long for Github, let me know if you want the whole thing sent separately**

```
[13:37:46]

[13:37:46] RUNNING HANDLER [restart uwsgi]
************************************************

[13:37:46] task path: /var/lib/ansible/local/handlers.yml:29

[13:37:48] <localhost> ESTABLISH LOCAL CONNECTION FOR USER: root

[13:37:48] <localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'

[13:37:48] <localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo
/root/.ansible/tmp `"&& mkdir
/root/.ansible/tmp/ansible-tmp-1643632668.480651-5872-192010482950157 &&
echo ansible-tmp-1643632668.480651-5872-192010482950157="` echo
/root/.ansible/tmp/ansible-tmp-1643632668.480651-5872-192010482950157 `" )
&& sleep 0'

[13:37:49] Using module file
/usr/lib/python3/dist-packages/ansible/modules/system/systemd.py

[13:37:49] <localhost> PUT
/root/.ansible/tmp/ansible-local-2298wrhhzlvi/tmptk8i8rgw TO
/root/.ansible/tmp/ansible-tmp-1643632668.480651-5872-192010482950157/Ansiba
llZ_systemd.py

[13:37:49] <localhost> EXEC /bin/sh -c 'chmod u+x
/root/.ansible/tmp/ansible-tmp-1643632668.480651-5872-192010482950157/
/root/.ansible/tmp/ansible-tmp-1643632668.480651-5872-192010482950157/Ansiba
llZ_systemd.py && sleep 0'

[13:37:49] <localhost> EXEC /bin/sh -c '/usr/bin/python
/root/.ansible/tmp/ansible-tmp-1643632668.480651-5872-192010482950157/Ansiba
llZ_systemd.py && sleep 0'

[13:38:38] <localhost> EXEC /bin/sh -c 'rm -f -r
/root/.ansible/tmp/ansible-tmp-1643632668.480651-5872-192010482950157/ >
/dev/null 2>&1 && sleep 0'

[13:38:41] changed: [localhost] => {

[13:38:41] "changed": true,

[13:38:41] "enabled": true,

[13:38:41] "invocation": {

[13:38:41] "module_args": {

[13:38:41] "daemon_reload": false,

[13:38:41] "enabled": true,

[13:38:41] "force": null,

[13:38:41] "masked": null,

[13:38:41] "name": "uwsgi",

[13:38:41] "no_block": false,

[13:38:41] "scope": null,

[13:38:41] "state": "restarted",

[13:38:41] "user": null

[13:38:41] }

[13:38:41] },

[13:38:41] "name": "uwsgi",

[13:38:41] "state": "started",

[13:38:41] "status": {

[13:38:41] "ActiveEnterTimestamp": "Mon 2022-01-31 12:55:57 CET",

[13:38:41] "ActiveEnterTimestampMonotonic": "247938403",

[13:38:41] "ActiveExitTimestampMonotonic": "0",

[13:38:41] "ActiveState": "active",

[13:38:41] "After": "systemd-journald.socket system.slice
network-online.target sysinit.target basic.target remote-fs.target",

[13:38:41] "AllowIsolate": "no",

[13:38:41] "AmbientCapabilities": "",

[13:38:41] "AssertResult": "yes",

[13:38:41] "AssertTimestamp": "Mon 2022-01-31 12:54:34 CET",

[13:38:41] "AssertTimestampMonotonic": "165185013",

[13:38:41] "Before": "multi-user.target graphical.target
shutdown.target",

[13:38:41] "BlockIOAccounting": "no",

[13:38:41] "BlockIOWeight": "[not set]",

[13:38:41] "CPUAccounting": "no",

[13:38:41] "CPUQuotaPerSecUSec": "infinity",

[13:38:41] "CPUSchedulingPolicy": "0",

[13:38:41] "CPUSchedulingPriority": "0",

[13:38:41] "CPUSchedulingResetOnFork": "no",

[13:38:41] "CPUShares": "[not set]",

[13:38:41] "CPUUsageNSec": "[not set]",

[13:38:41] "CPUWeight": "[not set]",

[13:38:41] "CacheDirectoryMode": "0755",

[13:38:41] "CanIsolate": "no",

[13:38:41] "CanReload": "yes",

[13:38:41] "CanStart": "yes",

[13:38:41] "CanStop": "yes",

[13:38:41] "CapabilityBoundingSet": "cap_chown cap_dac_override
cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid
cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast
cap_net_admin cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_module
cap_sys_rawio cap_sys_chroot cap_sys_ptrace cap_sys_pacct cap_sys_admin
cap_sys_boot cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config
cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap
cap_mac_override cap_mac_admin cap_syslog cap_wake_alarm cap_block_suspend",

[13:38:41] "CollectMode": "inactive",

[13:38:41] "ConditionResult": "yes",

[13:38:41] "ConditionTimestamp": "Mon 2022-01-31 12:54:34 CET",

[13:38:41] "ConditionTimestampMonotonic": "165184993",

[13:38:41] "ConfigurationDirectoryMode": "0755",

[13:38:41] "Conflicts": "shutdown.target",

[13:38:41] "ControlGroup": "/system.slice/uwsgi.service",

[13:38:41] "ControlPID": "0",

[13:38:41] "DefaultDependencies": "yes",

[13:38:41] "Delegate": "no",

[13:38:41] "Description": "LSB: Start/stop uWSGI server
instance(s)",

[13:38:41] "DevicePolicy": "auto",

[13:38:41] "Documentation": "man:systemd-sysv-generator(8)",

[13:38:41] "DynamicUser": "no",

[13:38:41] "ExecMainCode": "0",

[13:38:41] "ExecMainExitTimestampMonotonic": "0",

[13:38:41] "ExecMainPID": "0",

[13:38:41] "ExecMainStartTimestampMonotonic": "0",

[13:38:41] "ExecMainStatus": "0",

[13:38:41] "ExecReload": "{ path=/etc/init.d/uwsgi ;
argv[]=/etc/init.d/uwsgi reload ; ignore_errors=no ; start_time=[n/a] ;
stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }",

[13:38:41] "ExecStart": "{ path=/etc/init.d/uwsgi ;
argv[]=/etc/init.d/uwsgi start ; ignore_errors=no ; start_time=[n/a] ;
stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }",

[13:38:41] "ExecStop": "{ path=/etc/init.d/uwsgi ; argv[]=/etc/init.
d/uwsgi stop ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0
; code=(null) ; status=0/0 }",

[13:38:41] "FailureAction": "none",

[13:38:41] "FailureActionExitStatus": "-1",

[13:38:41] "FileDescriptorStoreMax": "0",

[13:38:41] "FinalKillSignal": "9",

[13:38:41] "FragmentPath":
"/run/systemd/generator.late/uwsgi.service",

[13:38:41] "GID": "[not set]",

[13:38:41] "GuessMainPID": "no",

[13:38:41] "IOAccounting": "no",

[13:38:41] "IOSchedulingClass": "0",

[13:38:41] "IOSchedulingPriority": "0",

[13:38:41] "IOWeight": "[not set]",

[13:38:41] "IPAccounting": "no",

[13:38:41] "IPEgressBytes": "18446744073709551615",

[13:38:41] "IPEgressPackets": "18446744073709551615",

[13:38:41] "IPIngressBytes": "18446744073709551615",

[13:38:41] "IPIngressPackets": "18446744073709551615",

[13:38:41] "Id": "uwsgi.service",

[13:38:41] "IgnoreOnIsolate": "no",

[13:38:41] "IgnoreSIGPIPE": "no",

[13:38:41] "InactiveEnterTimestampMonotonic": "0",

[13:38:41] "InactiveExitTimestamp": "Mon 2022-01-31 12:54:34 CET",

[13:38:41] "InactiveExitTimestampMonotonic": "165474579",

[13:38:41] "InvocationID": "26cb22579ced41a7a4043d5a178196d3",

[13:38:41] "JobRunningTimeoutUSec": "infinity",

[13:38:41] "JobTimeoutAction": "none",

[13:38:41] "JobTimeoutUSec": "infinity",

[13:38:41] "KeyringMode": "private",

[13:38:41] "KillMode": "process",

[13:38:41] "KillSignal": "15",

[13:38:41] "LimitAS": "infinity",

[13:38:41] "LimitASSoft": "infinity",

[13:38:41] "LimitCORE": "infinity",

[13:38:41] "LimitCORESoft": "0",

[13:38:41] "LimitCPU": "infinity",

[13:38:41] "LimitCPUSoft": "infinity",

[13:38:41] "LimitDATA": "infinity",

[13:38:41] "LimitDATASoft": "infinity",

[13:38:41] "LimitFSIZE": "infinity",

[13:38:41] "LimitFSIZESoft": "infinity",

[13:38:41] "LimitLOCKS": "infinity",

[13:38:41] "LimitLOCKSSoft": "infinity",

[13:38:41] "LimitMEMLOCK": "65536",

[13:38:41] "LimitMEMLOCKSoft": "65536",

[13:38:41] "LimitMSGQUEUE": "819200",

[13:38:41] "LimitMSGQUEUESoft": "819200",

[13:38:41] "LimitNICE": "0",

[13:38:41] "LimitNICESoft": "0",

[13:38:41] "LimitNOFILE": "524288",

[13:38:41] "LimitNOFILESoft": "1024",

[13:38:41] "LimitNPROC": "14124",

[13:38:41] "LimitNPROCSoft": "14124",

[13:38:41] "LimitRSS": "infinity",

[13:38:41] "LimitRSSSoft": "infinity",

[13:38:41] "LimitRTPRIO": "0",

[13:38:41] "LimitRTPRIOSoft": "0",

[13:38:41] "LimitRTTIME": "infinity",

[13:38:41] "LimitRTTIMESoft": "infinity",

[13:38:41] "LimitSIGPENDING": "14124",

[13:38:41] "LimitSIGPENDINGSoft": "14124",

[13:38:41] "LimitSTACK": "infinity",

[13:38:41] "LimitSTACKSoft": "8388608",

[13:38:41] "LoadState": "loaded",

[13:38:41] "LockPersonality": "no",

[13:38:41] "LogLevelMax": "-1",

[13:38:41] "LogRateLimitBurst": "0",

[13:38:41] "LogRateLimitIntervalUSec": "0",

[13:38:41] "LogsDirectoryMode": "0755",

[13:38:41] "MainPID": "0",

[13:38:41] "MemoryAccounting": "yes",

[13:38:41] "MemoryCurrent": "[not set]",

[13:38:41] "MemoryDenyWriteExecute": "no",

[13:38:41] "MemoryHigh": "infinity",

[13:38:41] "MemoryLimit": "infinity",

[13:38:41] "MemoryLow": "0",

[13:38:41] "MemoryMax": "infinity",

[13:38:41] "MemoryMin": "0",

[13:38:41] "MemorySwapMax": "infinity",

[13:38:41] "MountAPIVFS": "no",

[13:38:41] "MountFlags": "",

[13:38:41] "NFileDescriptorStore": "0",

[13:38:41] "NRestarts": "0",

[13:38:41] "Names": "uwsgi.service",

[13:38:41] "NeedDaemonReload": "no",

[13:38:41] "Nice": "0",

[13:38:41] "NoNewPrivileges": "no",

[13:38:41] "NonBlocking": "no",

[13:38:41] "NotifyAccess": "none",

[13:38:41] "OOMScoreAdjust": "0",

[13:38:41] "OnFailureJobMode": "replace",

[13:38:41] "Perpetual": "no",

[13:38:41] "PrivateDevices": "no",

[13:38:41] "PrivateMounts": "no",

[13:38:41] "PrivateNetwork": "no",

[13:38:41] "PrivateTmp": "no",

[13:38:41] "PrivateUsers": "no",

[13:38:41] "ProtectControlGroups": "no",

[13:38:41] "ProtectHome": "no",

[13:38:41] "ProtectKernelModules": "no",

[13:38:41] "ProtectKernelTunables": "no",

[13:38:41] "ProtectSystem": "no",

[13:38:41] "RefuseManualStart": "no",

[13:38:41] "RefuseManualStop": "no",

[13:38:41] "RemainAfterExit": "yes",

[13:38:41] "RemoveIPC": "no",

[13:38:41] "Requires": "sysinit.target system.slice",

[13:38:41] "Restart": "no",

[13:38:41] "RestartUSec": "100ms",

[13:38:41] "RestrictNamespaces": "no",

[13:38:41] "RestrictRealtime": "no",

[13:38:41] "Result": "success",

[13:38:41] "RootDirectoryStartOnly": "no",

[13:38:41] "RuntimeDirectoryMode": "0755",

[13:38:41] "RuntimeDirectoryPreserve": "no",

[13:38:41] "RuntimeMaxUSec": "infinity",

[13:38:41] "SameProcessGroup": "no",

[13:38:41] "SecureBits": "0",

[13:38:41] "SendSIGHUP": "no",

[13:38:41] "SendSIGKILL": "yes",

[13:38:41] "Slice": "system.slice",

[13:38:41] "SourcePath": "/etc/init.d/uwsgi",

[13:38:41] "StandardError": "inherit",

[13:38:41] "StandardInput": "null",

[13:38:41] "StandardInputData": "",

[13:38:41] "StandardOutput": "journal",

[13:38:41] "StartLimitAction": "none",

[13:38:41] "StartLimitBurst": "5",

[13:38:41] "StartLimitIntervalUSec": "10s",

[13:38:41] "StartupBlockIOWeight": "[not set]",

[13:38:41] "StartupCPUShares": "[not set]",

[13:38:41] "StartupCPUWeight": "[not set]",

[13:38:41] "StartupIOWeight": "[not set]",

[13:38:41] "StateChangeTimestamp": "Mon 2022-01-31 12:55:57 CET",

[13:38:41] "StateChangeTimestampMonotonic": "247938403",

[13:38:41] "StateDirectoryMode": "0755",

[13:38:41] "StatusErrno": "0",

[13:38:41] "StopWhenUnneeded": "no",

[13:38:41] "SubState": "running",

[13:38:41] "SuccessAction": "none",

[13:38:41] "SuccessActionExitStatus": "-1",

[13:38:41] "SyslogFacility": "3",

[13:38:41] "SyslogLevel": "6",

[13:38:41] "SyslogLevelPrefix": "yes",

[13:38:41] "SyslogPriority": "30",

[13:38:41] "SystemCallErrorNumber": "0",

[13:38:41] "TTYReset": "no",

[13:38:41] "TTYVHangup": "no",

[13:38:41] "TTYVTDisallocate": "no",

[13:38:41] "TasksAccounting": "yes",

[13:38:41] "TasksCurrent": "[not set]",

[13:38:41] "TasksMax": "4237",

[13:38:41] "TimeoutStartUSec": "5min",

[13:38:41] "TimeoutStopUSec": "5min",

[13:38:41] "TimerSlackNSec": "50000",

[13:38:41] "Transient": "no",

[13:38:41] "Type": "forking",

[13:38:41] "UID": "[not set]",

[13:38:41] "UMask": "0022",

[13:38:41] "UnitFilePreset": "enabled",

[13:38:41] "UnitFileState": "generated",

[13:38:41] "UtmpMode": "init",

[13:38:41] "WantedBy": "multi-user.target graphical.target",

[13:38:41] "Wants": "network-online.target",

[13:38:41] "WatchdogSignal": "6",

[13:38:41] "WatchdogTimestampMonotonic": "0",

[13:38:41] "WatchdogUSec": "0"

[13:38:41] }

[13:38:41] }

[13:38:41] META: ran handlers

[13:38:43]

[13:38:43] TASK [Heartbeat mode on KoomBook LED, update is over !!!]
**********************

[13:38:43] --> Heartbeat mode on KoomBook LED, update is over !!!

[13:38:43] [STAGE 3/6: Image configuration (virtualized) - 50%]

[13:38:43] task path: /var/lib/ansible/local/main.yml:112

[13:38:45] skipping: [localhost] => {

[13:38:45] "changed": false,

[13:38:45] "skip_reason": "Conditional result was False"

[13:38:45] }

[13:38:45] META: ran handlers

[13:38:45]

[13:38:45] PLAY RECAP
*********************************************************************

[13:38:45] localhost : ok=65 changed=46 unreachable=0
failed=0

[13:38:45]

[13:38:50] STDERR: [WARNING]: Consider using the unarchive module rather
than running tar. If

[13:38:50] STDERR: you need to use command because unarchive is insufficient
you can add

[13:38:50] STDERR: warn=False to this command task or set
command_warnings=False in ansible.cfg to

[13:38:50] STDERR: get rid of this message.

[13:38:50] sudo sync

[13:38:53] sudo shutdown -P 0

[13:39:00] STDERR: Shutdown scheduled for Mon 2022-01-31 13:38:58 CET, use
'shutdown -c' to cancel.

[13:39:30] VM is off.

[13:39:40] [STAGE 4/6: Copy contents onto image - 50%]

[13:39:40] --> Formating data partition on host

[13:39:40] Looking for C:\Windows\System32\imdisk.exe

[13:39:40] ImDisk already present.

[13:39:40] Call: ['wmic', 'logicaldisk', 'get', 'caption']

[13:39:40] Caption

[13:39:40]

[13:39:40] C:

[13:39:40]

[13:39:40] D:

[13:39:40]

[13:39:40] E:

[13:39:40]

[13:39:40] F:

[13:39:40]

[13:39:40]

[13:39:40]

[13:39:40] Call: ['net', 'use']

[13:39:40] Neue Verbindungen werden gespeichert.

[13:39:40]

[13:39:40] Es sind keine Eintr"ge in der Liste.

[13:39:40]

[13:39:40] Call: ['C:\\Windows\\System32\\imdisk.exe', '-a', '-f',
'D:\\hotspot-2022_01_31-11_58_04.BUILDING.img', '-o', 'rw', '-t', 'file',
'-v', '3', '-p', '/fs:exfat /V:HSPOT_DATA /q /y', '-m', 'G:']

[13:39:41] Call: ['C:\\Windows\\System32\\imdisk.exe', '-D', '-m', 'G:']

[13:39:41] Notifying applications...

[13:39:41] Flushing file buffers...

[13:39:41] Locking volume...

[13:39:41] Dismounting filesystem...

[13:39:41] Removing device...

[13:39:41] Removing mountpoint...

[13:39:41] Done.

[13:39:41]

--- Exception Trace ---

Traceback (most recent call last):

File "run_installation.py", line 329, in run_installation

File "backend\mount.py", line 418, in format_data_partition

File "backend\util.py", line 104, in subprocess_pretty_check_call

File "backend\util.py", line 86, in subprocess_pretty_call

File "subprocess.py", line 1121, in communicate

File "encodings\cp1252.py", line 23, in decode

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 290:
character maps to <undefined>



---

[13:39:41] Restoring system sleep policy

[13:39:41] Restoring ES_CONTINUOUS mode to current thread

[13:39:41] *** DURATIONS SUMMARY ***

[13:39:41] [1/6] Retrieve Master Image: 11 minutes and 13.91 seconds (31.01.
2022 11:58:04 to 31.01.2022 12:09:18)

[13:39:41] [2/6] Download contents: 14 minutes and 43.27 seconds (31.01.2022
12:09:18 to 31.01.2022 12:24:01)

[13:39:41] [3/6] Image configuration (virtualized): 1 hour, 15 minutes and
38.65 seconds (31.01.2022 12:24:01 to 31.01.2022 13:39:40)

[13:39:41] TOTAL: 1 hour, 41 minutes and 37.57 seconds (31.01.2022 11:58:04
to 31.01.2022 13:39:41)

[13:39:41] --> Failed: 'charmap' codec can't decode byte 0x81 in position

[13:39:41] Installation failed: 'charmap' codec can't decode byte 0x81 in
position 290: character maps to <undefined>

[13:39:41] [STAGE 4/6: Copy contents onto image - 67%]
```

**Comment by kelson42** [comment] 2022-02-01 12:15
Is a duplicate of #611.

This comment might be helpful to workaround the bug https://github.com/offspot/kiwix-hotspot/issues/611#issuecomment-881916358

**Closed by kelson42** 2022-02-01 12:15 UTC
Labels: bug
